version: '2'
services:
    testjhipsteronline-app:
        image: testjhipsteronline
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://testjhipsteronline-mysql:3306/testjhipsteronline?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testjhipsteronline-mysql:
        extends:
            file: mysql.yml
            service: testjhipsteronline-mysql
